### ISSUE TITLE
Not working on uma partition

### ISSUE THREAD

**Issue by Monumilnides** [theheroGAC/PSP-EMULATORS-INSTALLER#2]
The content of my adrenaline is installed in the UMA partition, and apparently this causes the emulators not to be installed.

**Comment by theheroGAC** [comment]
Please test this version https://github.com/theheroGAC/PSP-EMULATORS-INSTALLER/releases/tag/1.10

**Comment by Monumilnides** [comment]
This issue has been fixed. I have a query, the previous version has left residual files in my vita?

**Comment by theheroGAC** [comment]
No :)

**Comment by Monumilnides** [comment]
Muchas gracias!
