### ISSUE TITLE
Adrenaline black screen. 

### ISSUE THREAD

**Issue by pixelmultiplo** [theheroGAC/PSP-EMULATORS-INSTALLER#3]
My adrenaline is installed in the uma partition and i hit trinagle accordingly.
No errors, but when i start adrenaline i get only a black screen.

**Comment by pixelmultiplo** [comment]
Update, not only adrenaline but nothing started anymore (tried to open vitashell, console hanged).
Had to hard reset, after this all seems to work and emulators are installed.

**Comment by theheroGAC** [comment]
Work now?

**Comment by pixelmultiplo** [comment]
Yes, everything seems to work after the reboot. Thank you.
